### ISSUE TITLE
Advanced search - Additional Author/Creator name searches fail on known values

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#468] opened 2021-04-22 16:09 UTC
This ticket follows the advanced search configuration work in #419.

When searching on a known author, this seems to fail when searching for additional authors in the 7xx range. The [requested mappings are noted here](https://docs.google.com/document/d/1C0W4Za9x5nVvfRaLp2-H0H7VjDHtdq-sYNisQ1ue8rg/edit#), and include: 

- [author_addl_tesim](https://github.com/emory-libraries/blacklight-catalog/blob/e127cef94ca0e319b280c02f32dbbd45c5920859/lib/marc_indexer.rb#L163)*
- [author_tesim](https://github.com/emory-libraries/blacklight-catalog/blob/e127cef94ca0e319b280c02f32dbbd45c5920859/lib/marc_indexer.rb#L160)

*do we not have a _tesim version of this field? If not, should we use `author_addl_display_tesim` instead?

The following searches failed when testing on Additional Authors:

**Advanced Search that fails:**

https://blackcat-arch.library.emory.edu/catalog/990011061190302486
20th century etudes

Search for Author/Creator: Persichetti, Vincent [a 7xx/additional author/creator]
https://blackcat-arch.library.emory.edu/catalog?utf8=✓&range%5Bpub_date_isim%5D%5Bbegin%5D=&range%5Bpub_date_isim%5D%5Bend%5D=&op=AND&all_fields_advanced=&title_advanced=&author_advanced=Persichetti%2C+Vincent&subject_advanced=&title_series_advanced=&publisher_advanced=&identifier_advanced=&call_number_advanced=&range%5Bpub_date_isim%5D%5Bbegin%5D=&range%5Bpub_date_isim%5D%5Bend%5D=&sort=score+desc%2C+pub_date_isi+desc%2C+title_si+asc&search_field=advanced&commit=Advanced+Search

Other notes: A keyword search _Persichetti, Vincent_ finds this record; a basic author search on _Persichetti_ does not find this record.

**Author [1xx] search example that works**
Sample: 
https://blackcat-arch.library.emory.edu/catalog/9936516164102486
Using a 1xx author and keyword from a subject
https://blackcat-arch.library.emory.edu/catalog?utf8=✓&op=AND&all_fields_advanced=&title_advanced=&author_advanced=Kargon%2C+Robert+H.&title_series_advanced=&publisher_advanced=&identifier_advanced=&call_number_advanced=&range%5Bpub_date_isim%5D%5Bbegin%5D=&range%5Bpub_date_isim%5D%5Bend%5D=&sort=score+desc%2C+pub_date_isi+desc%2C+title_si+asc&search_field=advanced&commit=Advanced+Search

Advanced search on Author [7xx] of the above record that fails: "Fiss, Karen"
https://blackcat-arch.library.emory.edu/catalog?utf8=✓&range%5Bpub_date_isim%5D%5Bbegin%5D=&range%5Bpub_date_isim%5D%5Bend%5D=&op=AND&all_fields_advanced=&title_advanced=&author_advanced=Fiss%2C+Karen&subject_advanced=&title_series_advanced=&publisher_advanced=&identifier_advanced=&call_number_advanced=&range%5Bpub_date_isim%5D%5Bbegin%5D=&range%5Bpub_date_isim%5D%5Bend%5D=&sort=score+desc%2C+pub_date_isi+desc%2C+title_si+asc&search_field=advanced&commit=Advanced+Search

In SOLR (all author fields shown for reference):
 
```
"author_addl_display_tesim":["Fiss, Karen relator: author",
          "Low, Morris relator: author",
          "Molella, Arthur P., 1944- relator: author"],
        "author_addl_ssim":["Fiss, Karen",
          "Low, Morris",
          "Molella, Arthur P., 1944-"],
        "author_display_ssim":["Kargon, Robert H. (Robert Hugh), author"],
        "author_ssim":["Kargon, Robert H. (Robert Hugh)",
          "Fiss, Karen",
          "Low, Morris",
          "Molella, Arthur P., 1944-"],
        "author_ssm":["Kargon, Robert H. (Robert Hugh),"],
        "author_tesim":["Kargon, Robert H. (Robert Hugh), author"],
```

**Comment by lovinscari** [comment] 2021-05-06 10:27
@alexBLR and @eporter23 - I am going to close this issue as the work was completed as intended as demonstrated during the sprint demo yesterday. Any refinements or enhancements will be addressed in new tickets.

**Closed by lovinscari** 2021-05-06 10:27 UTC
Labels: Application Development, Search, bug
