### ISSUE TITLE
Alma API's Needed for Requesting

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#68] opened 2020-12-03 12:27 UTC
As the product owner, I would like to explore the functionality provided by the requesting API's in Alma in an effort to review and document workflows associated with requesting. The requests will also be used in MyAccount. From the documentation by ExLibris - https://developers.exlibrisgroup.com/alma/apis/users/, it is believed the following API's will be useful. It some instances with requesting (e.g. cancel request) it is assumed Blacklight is communicating back to Alma and will update Alma data accordingly. Each item listed below is considered an individual task/issues.

**Comment by rotated8** [comment] 2021-02-05 16:41
Duplicate of #125

**Closed by rotated8** 2021-02-05 16:41 UTC
